export default {
  data() {
    return {
      currentIndex: null,
      iconList: [{
        'className': 'el-icon-platform-eleme'
      }, {
        'className': 'el-icon-eleme'
      }, {
        'className': 'el-icon-delete-solid'
      }, {
        'className': 'el-icon-delete'
      }, {
        'className': 'el-icon-s-tools'
      }, {
        'className': 'el-icon-setting'
      }, {
        'className': 'el-icon-user-solid'
      }, {
        'className': 'el-icon-user'
      }, {
        'className': 'el-icon-phone'
      }, {
        'className': 'el-icon-phone-outline'
      }, {
        'className': 'el-icon-more'
      }, {
        'className': 'el-icon-more-outline'
      }, {
        'className': 'el-icon-star-on'
      }, {
        'className': 'el-icon-star-off'
      }, {
        'className': 'el-icon-s-goods'
      }, {
        'className': 'el-icon-goods'
      }, {
        'className': 'el-icon-warning'
      }, {
        'className': 'el-icon-warning-outline'
      }, {
        'className': 'el-icon-question'
      }, {
        'className': 'el-icon-info'
      }, {
        'className': 'el-icon-remove'
      }, {
        'className': 'el-icon-circle-plus'
      }, {
        'className': 'el-icon-success'
      }, {
        'className': 'el-icon-error'
      }, {
        'className': 'el-icon-zoom-in'
      }, {
        'className': 'el-icon-zoom-out'
      }, {
        'className': 'el-icon-remove-outline'
      }, {
        'className': 'el-icon-circle-plus-outline'
      }, {
        'className': 'el-icon-circle-check'
      }, {
        'className': 'el-icon-circle-close'
      }, {
        'className': 'el-icon-s-help'
      }, {
        'className': 'el-icon-help'
      }, {
        'className': 'el-icon-minus'
      }, {
        'className': 'el-icon-plus'
      }, {
        'className': 'el-icon-check'
      }, {
        'className': 'el-icon-close'
      }, {
        'className': 'el-icon-picture'
      }, {
        'className': 'el-icon-picture-outline'
      }, {
        'className': 'el-icon-picture-outline-round'
      }, {
        'className': 'el-icon-upload'
      }, {
        'className': 'el-icon-upload2'
      }, {
        'className': 'el-icon-download'
      }, {
        'className': 'el-icon-camera-solid'
      }, {
        'className': 'el-icon-camera'
      }, {
        'className': 'el-icon-video-camera-solid'
      }, {
        'className': 'el-icon-video-camera'
      }, {
        'className': 'el-icon-message-solid'
      }, {
        'className': 'el-icon-bell'
      }, {
        'className': 'el-icon-s-cooperation'
      }, {
        'className': 'el-icon-s-order'
      }, {
        'className': 'el-icon-s-platform'
      }, {
        'className': 'el-icon-s-fold'
      }, {
        'className': 'el-icon-s-unfold'
      }, {
        'className': 'el-icon-s-operation'
      }, {
        'className': 'el-icon-s-promotion'
      }, {
        'className': 'el-icon-s-home'
      }, {
        'className': 'el-icon-s-release'
      }, {
        'className': 'el-icon-s-ticket'
      }, {
        'className': 'el-icon-s-management'
      }, {
        'className': 'el-icon-s-open'
      }, {
        'className': 'el-icon-s-shop'
      }, {
        'className': 'el-icon-s-marketing'
      }, {
        'className': 'el-icon-s-flag'
      }, {
        'className': 'el-icon-s-comment'
      }, {
        'className': 'el-icon-s-finance'
      }, {
        'className': 'el-icon-s-claim'
      }, {
        'className': 'el-icon-s-custom'
      }, {
        'className': 'el-icon-s-opportunity'
      }, {
        'className': 'el-icon-s-data'
      }, {
        'className': 'el-icon-s-check'
      }, {
        'className': 'el-icon-s-grid'
      }, {
        'className': 'el-icon-menu'
      }, {
        'className': 'el-icon-share'
      }, {
        'className': 'el-icon-d-caret'
      }, {
        'className': 'el-icon-caret-left'
      }, {
        'className': 'el-icon-caret-right'
      }, {
        'className': 'el-icon-caret-bottom'
      }, {
        'className': 'el-icon-caret-top'
      }, {
        'className': 'el-icon-bottom-left'
      }, {
        'className': 'el-icon-bottom-right'
      }, {
        'className': 'el-icon-back'
      }, {
        'className': 'el-icon-right'
      }, {
        'className': 'el-icon-bottom'
      }, {
        'className': 'el-icon-top'
      }, {
        'className': 'el-icon-top-left'
      }, {
        'className': 'el-icon-top-right'
      }, {
        'className': 'el-icon-arrow-left'
      }, {
        'className': 'el-icon-arrow-right'
      }, {
        'className': 'el-icon-arrow-down'
      }, {
        'className': 'el-icon-arrow-up'
      }, {
        'className': 'el-icon-d-arrow-left'
      }, {
        'className': 'el-icon-d-arrow-right'
      }, {
        'className': 'el-icon-video-pause'
      }, {
        'className': 'el-icon-video-play'
      }, {
        'className': 'el-icon-refresh'
      }, {
        'className': 'el-icon-refresh-right'
      }, {
        'className': 'el-icon-refresh-left'
      }, {
        'className': 'el-icon-finished'
      }, {
        'className': 'el-icon-sort'
      }, {
        'className': 'el-icon-sort-up'
      }, {
        'className': 'el-icon-sort-down'
      }, {
        'className': 'el-icon-rank'
      }, {
        'className': 'el-icon-loading'
      }, {
        'className': 'el-icon-view'
      }, {
        'className': 'el-icon-c-scale-to-original'
      }, {
        'className': 'el-icon-date'
      }, {
        'className': 'el-icon-edit'
      }, {
        'className': 'el-icon-edit-outline'
      }, {
        'className': 'el-icon-folder'
      }, {
        'className': 'el-icon-folder-opened'
      }, {
        'className': 'el-icon-folder-add'
      }, {
        'className': 'el-icon-folder-remove'
      }, {
        'className': 'el-icon-folder-delete'
      }, {
        'className': 'el-icon-folder-checked'
      }, {
        'className': 'el-icon-tickets'
      }, {
        'className': 'el-icon-document-remove'
      }, {
        'className': 'el-icon-document-delete'
      }, {
        'className': 'el-icon-document-copy'
      }, {
        'className': 'el-icon-document-checked'
      }, {
        'className': 'el-icon-document'
      }, {
        'className': 'el-icon-document-add'
      }, {
        'className': 'el-icon-printer'
      }, {
        'className': 'el-icon-paperclip'
      }, {
        'className': 'el-icon-takeaway-box'
      }, {
        'className': 'el-icon-search'
      }, {
        'className': 'el-icon-monitor'
      }, {
        'className': 'el-icon-attract'
      }, {
        'className': 'el-icon-mobile'
      }, {
        'className': 'el-icon-scissors'
      }, {
        'className': 'el-icon-umbrella'
      }, {
        'className': 'el-icon-headset'
      }, {
        'className': 'el-icon-brush'
      }, {
        'className': 'el-icon-mouse'
      }, {
        'className': 'el-icon-coordinate'
      }, {
        'className': 'el-icon-magic-stick'
      }, {
        'className': 'el-icon-reading'
      }, {
        'className': 'el-icon-data-line'
      }, {
        'className': 'el-icon-data-board'
      }, {
        'className': 'el-icon-pie-chart'
      }, {
        'className': 'el-icon-data-analysis'
      }, {
        'className': 'el-icon-collection-tag'
      }, {
        'className': 'el-icon-film'
      }, {
        'className': 'el-icon-suitcase'
      }, {
        'className': 'el-icon-suitcase-1'
      }, {
        'className': 'el-icon-receiving'
      }, {
        'className': 'el-icon-collection'
      }, {
        'className': 'el-icon-files'
      }, {
        'className': 'el-icon-notebook-1'
      }, {
        'className': 'el-icon-notebook-2'
      }, {
        'className': 'el-icon-toilet-paper'
      }, {
        'className': 'el-icon-office-building'
      }, {
        'className': 'el-icon-school'
      }, {
        'className': 'el-icon-table-lamp'
      }, {
        'className': 'el-icon-house'
      }, {
        'className': 'el-icon-no-smoking'
      }, {
        'className': 'el-icon-smoking'
      }, {
        'className': 'el-icon-shopping-cart-full'
      }, {
        'className': 'el-icon-shopping-cart-1'
      }, {
        'className': 'el-icon-shopping-cart-2'
      }, {
        'className': 'el-icon-shopping-bag-1'
      }, {
        'className': 'el-icon-shopping-bag-2'
      }, {
        'className': 'el-icon-sold-out'
      }, {
        'className': 'el-icon-sell'
      }, {
        'className': 'el-icon-present'
      }, {
        'className': 'el-icon-box'
      }, {
        'className': 'el-icon-bank-card'
      }, {
        'className': 'el-icon-money'
      }, {
        'className': 'el-icon-coin'
      }, {
        'className': 'el-icon-wallet'
      }, {
        'className': 'el-icon-discount'
      }, {
        'className': 'el-icon-price-tag'
      }, {
        'className': 'el-icon-news'
      }, {
        'className': 'el-icon-guide'
      }, {
        'className': 'el-icon-male'
      }, {
        'className': 'el-icon-female'
      }, {
        'className': 'el-icon-thumb'
      }, {
        'className': 'el-icon-cpu'
      }, {
        'className': 'el-icon-link'
      }, {
        'className': 'el-icon-connection'
      }, {
        'className': 'el-icon-open'
      }, {
        'className': 'el-icon-turn-off'
      }, {
        'className': 'el-icon-set-up'
      }, {
        'className': 'el-icon-chat-round'
      }, {
        'className': 'el-icon-chat-line-round'
      }, {
        'className': 'el-icon-chat-square'
      }, {
        'className': 'el-icon-chat-dot-round'
      }, {
        'className': 'el-icon-chat-dot-square'
      }, {
        'className': 'el-icon-chat-line-square'
      }, {
        'className': 'el-icon-message'
      }, {
        'className': 'el-icon-postcard'
      }, {
        'className': 'el-icon-position'
      }, {
        'className': 'el-icon-turn-off-microphone'
      }, {
        'className': 'el-icon-microphone'
      }, {
        'className': 'el-icon-close-notification'
      }, {
        'className': 'el-icon-bangzhu'
      }, {
        'className': 'el-icon-time'
      }, {
        'className': 'el-icon-odometer'
      }, {
        'className': 'el-icon-crop'
      }, {
        'className': 'el-icon-aim'
      }, {
        'className': 'el-icon-switch-button'
      }, {
        'className': 'el-icon-full-screen'
      }, {
        'className': 'el-icon-copy-document'
      }, {
        'className': 'el-icon-mic'
      }, {
        'className': 'el-icon-stopwatch'
      }, {
        'className': 'el-icon-medal-1'
      }, {
        'className': 'el-icon-medal'
      }, {
        'className': 'el-icon-trophy'
      }, {
        'className': 'el-icon-trophy-1'
      }, {
        'className': 'el-icon-first-aid-kit'
      }, {
        'className': 'el-icon-discover'
      }, {
        'className': 'el-icon-place'
      }, {
        'className': 'el-icon-location'
      }, {
        'className': 'el-icon-location-outline'
      }, {
        'className': 'el-icon-location-information'
      }, {
        'className': 'el-icon-add-location'
      }, {
        'className': 'el-icon-delete-location'
      }, {
        'className': 'el-icon-map-location'
      }, {
        'className': 'el-icon-alarm-clock'
      }, {
        'className': 'el-icon-timer'
      }, {
        'className': 'el-icon-watch-1'
      }, {
        'className': 'el-icon-watch'
      }, {
        'className': 'el-icon-lock'
      }, {
        'className': 'el-icon-unlock'
      }, {
        'className': 'el-icon-key'
      }, {
        'className': 'el-icon-service'
      }, {
        'className': 'el-icon-mobile-phone'
      }, {
        'className': 'el-icon-bicycle'
      }, {
        'className': 'el-icon-truck'
      }, {
        'className': 'el-icon-ship'
      }, {
        'className': 'el-icon-basketball'
      }, {
        'className': 'el-icon-football'
      }, {
        'className': 'el-icon-soccer'
      }, {
        'className': 'el-icon-baseball'
      }, {
        'className': 'el-icon-wind-power'
      }, {
        'className': 'el-icon-light-rain'
      }, {
        'className': 'el-icon-lightning'
      }, {
        'className': 'el-icon-heavy-rain'
      }, {
        'className': 'el-icon-sunrise'
      }, {
        'className': 'el-icon-sunrise-1'
      }, {
        'className': 'el-icon-sunset'
      }, {
        'className': 'el-icon-sunny'
      }, {
        'className': 'el-icon-cloudy'
      }, {
        'className': 'el-icon-partly-cloudy'
      }, {
        'className': 'el-icon-cloudy-and-sunny'
      }, {
        'className': 'el-icon-moon'
      }, {
        'className': 'el-icon-moon-night'
      }, {
        'className': 'el-icon-dish'
      }, {
        'className': 'el-icon-dish-1'
      }, {
        'className': 'el-icon-food'
      }, {
        'className': 'el-icon-chicken'
      }, {
        'className': 'el-icon-fork-spoon'
      }, {
        'className': 'el-icon-knife-fork'
      }, {
        'className': 'el-icon-burger'
      }, {
        'className': 'el-icon-tableware'
      }, {
        'className': 'el-icon-sugar'
      }, {
        'className': 'el-icon-dessert'
      }, {
        'className': 'el-icon-ice-cream'
      }, {
        'className': 'el-icon-hot-water'
      }, {
        'className': 'el-icon-water-cup'
      }, {
        'className': 'el-icon-coffee-cup'
      }, {
        'className': 'el-icon-cold-drink'
      }, {
        'className': 'el-icon-goblet'
      }, {
        'className': 'el-icon-goblet-full'
      }, {
        'className': 'el-icon-goblet-square'
      }, {
        'className': 'el-icon-goblet-square-full'
      }, {
        'className': 'el-icon-refrigerator'
      }, {
        'className': 'el-icon-grape'
      }, {
        'className': 'el-icon-watermelon'
      }, {
        'className': 'el-icon-cherry'
      }, {
        'className': 'el-icon-apple'
      }, {
        'className': 'el-icon-pear'
      }, {
        'className': 'el-icon-orange'
      }, {
        'className': 'el-icon-coffee'
      }, {
        'className': 'el-icon-ice-tea'
      }, {
        'className': 'el-icon-ice-drink'
      }, {
        'className': 'el-icon-milk-tea'
      }, {
        'className': 'el-icon-potato-strips'
      }, {
        'className': 'el-icon-lollipop'
      }, {
        'className': 'el-icon-ice-cream-square'
      }, {
        'className': 'el-icon-ice-cream-round'
      }]
    }
  }
}
